name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          git fetch --prune
          git push --delete origin ${{ github.event.pull_request.head.ref }}
