name: Deploy Next.js PR Preview to Pages

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAGIC_SECRET }}

      - name: Detect package manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ env.manager }}

      - name: Install dependencies
        run: ${{ env.manager }} ${{ env.command }}

      - name: Build with Next.js
        run: ${{ env.runner }} next build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MAGIC_SECRET }}
          publish_dir: .next
          cname: ${{ github.repository }}

      - name: Get deployment URL
        run: echo "Deployment  https://$GITHUB_REPOSITORY.github.io/$GITHUB_SHA/"

      - name: Output deployment URL
        run: echo "::set-output name=deployment_url::https://$GITHUB_REPOSITORY.github.io/$GITHUB_SHA/"
        id: set_output

      - name: Show deployment URL
        run: echo "Deployment  ${{ steps.set_output.outputs.deployment_url }}"
