name: PR deploy (working link)

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAGIC_SECRET }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ env.manager }}

      - name: Install dependencies
        run: npm run install

      - name: Build build
        run: npm run build

      - name: Run export
        run: npm run export

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.MAGIC_SECRET }}
          source-dir: out
