name: PR deploy (working link)

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAGIC_SECRET }}

      - name: Detect package manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ env.manager }}

      - name: Install dependencies
        run: ${{ env.manager }} ${{ env.command }}

      - name: Build with Next.js
        run: ${{ env.runner }} next build

      - name: Build with Next.js
        run: ${{ env.runner }} next export

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.MAGIC_SECRET }}
          source-dir: ./out
